### ISSUE TITLE
OrderMap 1.0 Roadmap

### ISSUE THREAD

**Issue by bluss** [bluss/indexmap#37]
### Must have

  * [x] Full consistency check list should be complete and remaining discrepancies should be fixable backwards compatibly or marked as not important (#19)
  * [x] Mutable keys #7 #39
  * [x] Settle crate name #14 ~~Settle removal semantics #15  (and split crate for full insertion order #12)~~
  * [x] Move map stuff to `map::` submodule (like `set::`) #60

### Nice to have
(can be added backwards compatibly)

  * [ ] Full consistency (#19). Being drop in is good, but some of the details don't matter much, you can be effectively drop in without being 100% type by type compatible.
  * [x] OrderSet #8 
  * [x] Order preserving retain #56 
  * [ ] Every public item has documentation

 ### At Release

* Blog post about the name change and explain the properties of the data structure

**Comment by bluss** [comment]
Next version will be the last with the ordermap name. Then we make one with the same version and compatible API under the new name (`IndexMap` as of this writing).

**Comment by bluss** [comment]
Crate name question is decided, `IndexMap` from #14
